version: "3"

services:
  reverse-proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external:
      name: "${NETWORK_NAME:-web}"
